### ISSUE TITLE
yaml config for extending scheduled tasks

### ISSUE THREAD

**Issue by ashmastaflash** [ashmastaflash/halocelery#24]
Containerized application can optionally consume a yaml configuration file, which will extend existing scheduled task configuration.

Structure:
```
- job_name: my_job
  job_type: daily
  hour: 12
  minute: 30
  retry: 5
  container: docker.io/myaccount/container1:v0.1
  args:
    FOO: BAR
    VAR2: VAL2
  args_exp:
    HELLO: WORLD

```

Only support daily tasks at first, if we need more scheduling options, we'll add them later.

Fields:
job_name: Name of job.  This should be unique.  Later re-statements of the same name will override any prior configurations under the same name.
job_type: Only `daily` is supported
hour: hour for scheduled task to run (0-23)
minute: 0-59
retry: Number of times to retry the job
container: Name of container to run (docker.io/myaccount/notifyuser:v0.1)
args: Arguments to be passed in as environment variables
args_exp: Arguments to be expanded by Celery when running the task.

Depends on https://github.com/cloudpassage/halocelery/issues/23
